id: I0DA53631
ocr_import_info:
  timestamp: '2023-08-15T02:12:35.544948+00:00'
  batch_id: batch-ffc9
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Tenzin Jordhen
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-08-15 02:34:26.746005+00:00
last_modified: 2023-08-15 02:34:26.746011+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN7886
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN7886
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་རྩ་བ་ཤེས་རབ་ཀྱི་རྩ་འགྲེལ་གཅེས་བཏུས།
  languages:
  - bo
  author: རྨ་བྱ་བྱང་ཆུབ་བརྩོན་འགྲུས།
statistics:
  ocr_word_mean_confidence_index: 0.9986135021882119
  ocr_word_median_confidence_index: 1.0
bases:
  I3CN7888:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7888
      total_pages: 778
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN7888.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9986135021882119
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
